services:
  react:
    image: choseongwoo/coffeee-client-react:v0716
    container_name: frontend
    build:
      context: .
      target: dev-envs
    ports:
      - "80:3000"
      - "3000:3000"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.production



